sudo: required
services:
  - docker

before_install:
  - docker build -t nikmasdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nikmasdev/react-test npm test

after_success:
  - docker build -t nikmasdev/multi-client ./client
  - docker build -t nikmasdev/multi-nginx ./nginx
  - docker build -t nikmasdev/multi-server ./server
  - docker build -t nikmasdev/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push nikmasdev/multi-client
  - docker push nikmasdev/multi-nginx 
  - docker push nikmasdev/multi-server
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-359455030060'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  